#!/usr/bin/env python3
"""
build_index_md.py: generate the pack's slide index from extracted titles.

Reads .corpus/titles.tsv (produced by extract_terms.py) and writes a page-
accurate, auto-generated index to the pack's slide-index.md with two views:
  1. By book, in page order:  the "flip to the page" reading index
  2. Alphabetical by title:    the exam-day lookup index

Only slide/section TITLES and page numbers are emitted (headings + pointers,
not reproduced courseware). The server reads this file straight from the
pack. It is a FIRST PASS: auto-extraction leaves some noise; curate as you
study.

Usage:  python3 scripts/build_index_md.py
"""

import os
import re
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pack_manifest import pack_dir, raw_course

TITLES = os.path.join(str(pack_dir()), ".corpus", "titles.tsv")
OUT = os.path.join(str(pack_dir()), "slide-index.md")

BOOK_ORDER = [str(b["label"]) for b in raw_course(pack_dir()).get("books") or []]
COURSE_NAME = str(raw_course(pack_dir()).get("name") or "Course")


def load_titles():
    if not os.path.isfile(TITLES):
        sys.exit("ERROR: run scripts/extract_terms.py first (no titles.tsv).")
    rows = []
    with open(TITLES, encoding="utf-8") as f:
        f.readline()  # header
        for line in f:
            if not line.strip():
                continue
            book, printed, pdf, title = line.rstrip("\n").split("\t", 3)
            rows.append((book, int(printed), int(pdf), title))
    return rows


URL_RE = re.compile(r"https?://|www\.")
LIST_MARKER_RE = re.compile(r"^\s*\d+[.)]\s+")


def looks_meaningful(title):
    """Keep only entries useful as alphabetical index anchors.

    Drops URLs, numbered list items, questions, and long body sentences that
    slip through when a slide has no distinct title.
    """
    t = title.strip()
    if URL_RE.search(t):
        return False
    if t.endswith("?"):                       # workbook questions
        return False
    if LIST_MARKER_RE.match(t):               # "1. ...", "10) ..." list items
        return False
    core = t.lstrip("•-–— ").strip()
    if len(core) < 6:
        return False
    if len(core.split()) > 12:                # body sentence, not a title
        return False
    if " " not in core and len(core) > 24:    # base64/hash token, not a term
        return False
    letters = sum(c.isalpha() for c in core)
    return letters >= 4


def main():
    rows = load_titles()

    by_book = defaultdict(list)
    for book, printed, pdf, title in rows:
        by_book[book].append((printed, pdf, title))

    alpha = sorted(
        ((title, book, printed) for book, printed, pdf, title in rows
         if looks_meaningful(title) and printed >= 1),
        key=lambda t: (t[0].lower(), t[1], t[2]),
    )

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(f"# {COURSE_NAME} Slide Index (auto-generated)\n\n")
        f.write("> Generated by `scripts/build_index_md.py` from slide/section "
                "titles. Page numbers are the **printed book page** (the number "
                "on the page), calibrated from each book's page header/footer. "
                "This is a first-pass backbone: expect some noisy rows from the "
                "watermarked source. Curate into `glossary.md` / "
                "`frameworks.md` as you study.\n\n")
        f.write(f"Books indexed: {len([b for b in BOOK_ORDER if b in by_book])} · "
                f"Total entries: {len(rows)}\n\n")

        f.write("## Alphabetical lookup (exam-day index)\n\n")
        f.write("| Term / Slide title | Book | Page |\n|---|---|---|\n")
        for title, book, printed in alpha:
            safe = title.replace("|", "\\|")
            f.write(f"| {safe} | {book} | {printed} |\n")

        f.write("\n## By book, in page order\n\n")
        for book in BOOK_ORDER:
            if book not in by_book:
                continue
            f.write(f"### {book}\n\n")
            f.write("| Page | Slide title |\n|---|---|\n")
            for printed, pdf, title in sorted(by_book[book]):
                if printed < 1:
                    continue
                safe = title.replace("|", "\\|")
                f.write(f"| {printed} | {safe} |\n")
            f.write("\n")

    print(f"Wrote {OUT}")
    print(f"  {len(alpha)} alphabetical entries, {len(rows)} total rows.")


if __name__ == "__main__":
    main()
